-- MySQL Script generated by MySQL Workbench
-- Fri 11 Jul 2014 18:41:23 BST
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema unk-nar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `unk-nar` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `unk-nar` ;

-- -----------------------------------------------------
-- Table `unk-nar`.`Area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unk-nar`.`Area` (
  `ID` VARCHAR(32) NOT NULL,
  `ID_Area__up` VARCHAR(32) NULL,
  `ID_Area__down` VARCHAR(32) NULL,
  `ID_Area__left` VARCHAR(32) NULL,
  `ID_Area__right` VARCHAR(32) NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_Area__Area__up_idx` (`ID_Area__up` ASC),
  INDEX `FK_Area__Area__down_idx` (`ID_Area__down` ASC),
  INDEX `FK_Area__Area__left_idx` (`ID_Area__left` ASC),
  INDEX `FK_Area__Area__right_idx` (`ID_Area__right` ASC),
  CONSTRAINT `FK_Area__Area__up`
    FOREIGN KEY (`ID_Area__up`)
    REFERENCES `unk-nar`.`Area` (`ID`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `FK_Area__Area__down`
    FOREIGN KEY (`ID_Area__down`)
    REFERENCES `unk-nar`.`Area` (`ID`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `FK_Area__Area__left`
    FOREIGN KEY (`ID_Area__left`)
    REFERENCES `unk-nar`.`Area` (`ID`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `FK_Area__Area__right`
    FOREIGN KEY (`ID_Area__right`)
    REFERENCES `unk-nar`.`Area` (`ID`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unk-nar`.`Player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unk-nar`.`Player` (
  `ID` VARCHAR(128) NOT NULL COMMENT 'Cookie from browser',
  `ID_Area` VARCHAR(32) NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_Player__Area_idx` (`ID_Area` ASC),
  CONSTRAINT `FK_Player__Area`
    FOREIGN KEY (`ID_Area`)
    REFERENCES `unk-nar`.`Area` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unk-nar`.`Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unk-nar`.`Item` (
  `ID` VARCHAR(32) NOT NULL,
  `maxUse` INT NULL,
  `perishAfter` TIME NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unk-nar`.`Item_in_Area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unk-nar`.`Item_in_Area` (
  `ID_Item` VARCHAR(32) NOT NULL,
  `ID_Area` VARCHAR(32) NOT NULL,
  `count` INT NULL,
  PRIMARY KEY (`ID_Item`, `ID_Area`),
  INDEX `FK_Item_in_Area__Area_idx` (`ID_Area` ASC),
  CONSTRAINT `FK_Item_in_Area__Item`
    FOREIGN KEY (`ID_Item`)
    REFERENCES `unk-nar`.`Item` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Item_in_Area__Area`
    FOREIGN KEY (`ID_Area`)
    REFERENCES `unk-nar`.`Area` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unk-nar`.`Player_has_Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unk-nar`.`Player_has_Item` (
  `ID_Player` VARCHAR(128) NOT NULL,
  `ID_Item` VARCHAR(32) NOT NULL,
  `count` INT NULL,
  PRIMARY KEY (`ID_Player`, `ID_Item`),
  INDEX `FK_Player_has_Item__Item_idx` (`ID_Item` ASC),
  CONSTRAINT `FK_Player_has_Item__Player`
    FOREIGN KEY (`ID_Player`)
    REFERENCES `unk-nar`.`Player` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Player_has_Item__Item`
    FOREIGN KEY (`ID_Item`)
    REFERENCES `unk-nar`.`Item` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unk-nar`.`Narrative`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unk-nar`.`Narrative` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `content` TEXT NOT NULL,
  `blurb` VARCHAR(32) NULL,
  `maxRepetition` INT NULL,
  `minRepetitionDelay` TIME NULL,
  `ID_Narrative_Choice__requirement` INT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unk-nar`.`Narrative_Item_Condition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unk-nar`.`Narrative_Item_Condition` (
  `ID` INT NOT NULL,
  `ID_Narrative` INT NOT NULL,
  `ID_Item` VARCHAR(32) NOT NULL,
  `itemInPocketCount` INT NULL,
  `itemInAreaCount` INT NULL,
  `itemSeenCount` INT NULL,
  `itemInPocketDuration` TIME NULL,
  `itemInAreaDuration` TIME NULL,
  `itemSeenDuration` TIME NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_Narrative_Item_Condition__Narrative_idx` (`ID_Narrative` ASC),
  INDEX `FK_Narrative_Item_Condition__Item_idx` (`ID_Item` ASC),
  CONSTRAINT `FK_Narrative_Item_Condition__Narrative`
    FOREIGN KEY (`ID_Narrative`)
    REFERENCES `unk-nar`.`Narrative` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Narrative_Item_Condition__Item`
    FOREIGN KEY (`ID_Item`)
    REFERENCES `unk-nar`.`Item` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unk-nar`.`Narrative_Area_Condition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unk-nar`.`Narrative_Area_Condition` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ID_Narrative` INT NOT NULL,
  `ID_Area` VARCHAR(32) NOT NULL,
  `areaVisitCount` INT NULL,
  `areaVisitDuration` TIME NULL,
  `areaKnownDuration` TIME NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_Narrative_Area_Condition__Narrative_idx` (`ID_Narrative` ASC),
  INDEX `FK_Narrative_Area_Condition__Area_idx` (`ID_Area` ASC),
  CONSTRAINT `FK_Narrative_Area_Condition__Narrative`
    FOREIGN KEY (`ID_Narrative`)
    REFERENCES `unk-nar`.`Narrative` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Narrative_Area_Condition__Area`
    FOREIGN KEY (`ID_Area`)
    REFERENCES `unk-nar`.`Area` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unk-nar`.`Narrative_Choice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unk-nar`.`Narrative_Choice` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ID_Narrative` INT NOT NULL,
  `choiceText` VARCHAR(32) NOT NULL,
  `content` TEXT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_Narrative_Choice__Narrative_idx` (`ID_Narrative` ASC),
  CONSTRAINT `FK_Narrative_Choice__Narrative`
    FOREIGN KEY (`ID_Narrative`)
    REFERENCES `unk-nar`.`Narrative` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unk-nar`.`Player_made_Narrative_Choice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unk-nar`.`Player_made_Narrative_Choice` (
  `ID_Player` VARCHAR(128) NOT NULL,
  `ID_Narrative_Choice` INT NOT NULL,
  PRIMARY KEY (`ID_Player`, `ID_Narrative_Choice`),
  INDEX `FK_Player_made_Narrative_Choice__Narrative_Choice_idx` (`ID_Narrative_Choice` ASC),
  CONSTRAINT `FK_Player_made_Narrative_Choice__Player`
    FOREIGN KEY (`ID_Player`)
    REFERENCES `unk-nar`.`Player` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Player_made_Narrative_Choice__Narrative_Choice`
    FOREIGN KEY (`ID_Narrative_Choice`)
    REFERENCES `unk-nar`.`Narrative_Choice` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
